version: '3'

services:
  app:
    container_name: api-bull
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn start:dev'
    ports:
      - '${PORT_CONTAINER}:${PORT_CONTAINER}'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - bull-net

  redis:
    image: redis
    container_name: redis-server
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - bull-net
    volumes:
      - cache:/data

networks:
  bull-net:
    driver: bridge

volumes:
  api-bull:
  cache:
